### ISSUE TITLE
Make Datetime postion encoding use multiple Fourier features

### ISSUE THREAD

**Issue by jacobbieker** [openclimatefix/nowcasting_dataloader#50] opened 2021-11-11 11:32 UTC
## Detailed Description
Currently time features are just the value of a single sin/cos. The spatial features use multiple sin/cos in their fourier encoding, so adding that to the datetime featurtes could make it easier for the model to figure things out, especially for timesteps that are close to each other.

**Comment by JackKelly** [comment] 2021-11-11 13:03
Is this a duplicate of #38?  (Or maybe this is a special case of #38?) :slightly_smiling_face:

**Comment by jacobbieker** [comment] 2021-11-15 11:48
A special case I guess? Its essentially the same thing, by adding more sin/cosines but is not explicitly putting it as every 6 hours or 2 hours, etc.

**Closed** 2021-11-17 16:46 UTC
Labels: enhancement
